Add subscribe command to follow Secret Manager Event Notifications
jenkins-x/gsm-controller pull request #24
Opened 2022-04-21 23:59 UTC by cakemanny

This resolves #23.  That is, it enables near-realtime updates in the cluster when new versions are added by following
`SECRET_VERSION_ADD` messages under the `subscribe` sub-command.

I've been running this in our development cluster for a couple of weeks now, and it seems to be working ok.

I've today added extra info to the docs and updated the  helm chart  today.

<details>
<summary>and checked the helm chart</summary>

```
~/src/go/gsm-controller/charts/gsm-controller (pubsub) % helm lint
==> Linting .
[WARNING] templates/cronjob.yaml: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob

1 chart(s) linted, 0 chart(s) failed
~/src/go/gsm-controller/charts/gsm-controller (pubsub) % helm lint --set allNamespace=true
==> Linting .
[WARNING] templates/cronjob.yaml: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob

1 chart(s) linted, 0 chart(s) failed
~/src/go/gsm-controller/charts/gsm-controller (pubsub) % helm lint --set deployment.pubsub.enabled=true
==> Linting .
[WARNING] templates/cronjob.yaml: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob

1 chart(s) linted, 0 chart(s) failed
```

```
~/src/go/gsm-controller/charts/gsm-controller (pubsub) % helm template . --set projectID=fir-project-1fc35 --set deployment.pubsub.enabled=true --set deployment.pubsub.subscription=secrets.events  --set cron.schedule="23 */2 * * *"  | k apply -f -
role.rbac.authorization.k8s.io/release-name-gsm-controller unchanged
rolebinding.rbac.authorization.k8s.io/release-name-gsm-controller unchanged
deployment.apps/release-name-gsm-controller configured
Warning: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
cronjob.batch/release-name-gsm-controller configured
```

</details>

There's also an update to the helm chart to allow adding the `--all-namespaces` flag with `helm install --set allNamespaces=true`

2024-03-02 12:26 UTC, msvticket commented
/ok-to-test

2024-03-04 19:13 UTC, cakemanny commented
The link to the run details is behind an authentication prompt
> [link](http://dashboard-jx.infra.jenkins-x.rocks/namespaces/jx/pipelineruns/enkins-x-gsm-controller-pr-24-pr-lpksv)

I wasn't able to find any mention of that on the [contributing page](https://jenkins-x.io/community/code/) .

Any idea why it's failing?

2024-03-05 23:20 UTC, msvticket commented
It didn't start at all du to too high resource request. See https://jenkins-x.io/blog/2022/04/22/kubernetes-1.22-tekton/

2024-03-11 08:53 UTC, msvticket commented
The reason I haven't merged this is that the release pipeline didn't go through. I have fixed the changelog step, but then the release binary step failed. As far as I can see that step is superfluous; I don't see any point at generating any artifacts other than the image and chart. So I have now removed that.

I say we first get the go upgrade done and then merge this.

2024-03-11 13:05 UTC, msvticket requested changes
Now the upgrade to go 1.19 is done. But that made this PR get a conflict with master. Please resolve that!

2024-03-11 20:29 UTC, cakemanny commented
Resolved!

2024-03-12 07:16 UTC, msvticket approved these changes

2024-03-12 07:17 UTC, merged