chore: add maintainers
jenkins-x/gsm-controller pull request #27
Opened 2023-05-02 10:14 UTC by tomhobson

2023-05-02 10:14 UTC, tomhobson commented
/cc @msvticket @babadofar @ankitm123

2023-05-02 10:23 UTC, babadofar approved these changes

2023-05-02 10:53 UTC, msvticket requested changes

2023-05-02 10:53 UTC, msvticket commented on OWNERS
> +- maintainers
For this to work you need the appropriate OWNERS_ALIASES file

2023-07-24 12:36 UTC, msvticket approved these changes

2023-07-24 12:40 UTC, merged